// Product metadata generated by analyze.py; descriptions reworked for natural, varied copy.
window.SITE = window.SITE || {};
window.SITE.PRODUCTS = [
  {
    "id": "ra-001",
    "sku": "RA #001",
    "name": "Gilded Current",
    "family": "Golden Hour",
    "accent": "#887959",
    "imgCard": "assets/products/ra-001-card.webp",
    "imgDetail": "assets/products/ra-001-detail.webp",
    "price": 219,
    "desc": "Warm, light-catching relief gives Gilded Current its glow, with fine ridges that shift through the day. Hand-finished to order in archival pigment, it arrives ready to anchor a room.",
    "collections": [
      "bestseller"
    ],
    "familyId": "golden-hour"
  },
  {
    "id": "ra-002",
    "sku": "RA #002",
    "name": "Sienna Strata",
    "family": "Terracotta & Earth",
    "accent": "#923C23",
    "imgCard": "assets/products/ra-002-card.webp",
    "imgDetail": "assets/products/ra-002-detail.webp",
    "price": 239,
    "desc": "Deep, earthen relief gives Sienna Strata its grounded, tactile presence. Each piece is made to order, so the relief and color read exactly as you see them here.",
    "collections": [
      "bestseller"
    ],
    "familyId": "terracotta"
  },
  {
    "id": "ra-003",
    "sku": "RA #003",
    "name": "Rust Texture",
    "family": "Terracotta & Earth",
    "accent": "#C97623",
    "imgCard": "assets/products/ra-003-card.webp",
    "imgDetail": "assets/products/ra-003-detail.webp",
    "price": 259,
    "desc": "Clay-toned layers build Rust Texture into a calm, rooted focal point. Crafted to order and sealed for longevity, it suits a living room, studio, or hallway.",
    "collections": [
      "bestseller"
    ],
    "familyId": "terracotta"
  },
  {
    "id": "ra-004",
    "sku": "RA #004",
    "name": "Terra Surface",
    "family": "Terracotta & Earth",
    "accent": "#422F22",
    "imgCard": "assets/products/ra-004-card.webp",
    "imgDetail": "assets/products/ra-004-detail.webp",
    "price": 209,
    "desc": "Rust and sienna ridges run through Terra Surface like sediment pressed into canvas. Made to order on textured canvas, it makes a calm focal point above a sofa or console.",
    "collections": [
      "bestseller"
    ],
    "familyId": "terracotta"
  },
  {
    "id": "ra-005",
    "sku": "RA #005",
    "name": "Solstice Depth",
    "family": "Golden Hour",
    "accent": "#B0A492",
    "imgCard": "assets/products/ra-005-card.webp",
    "imgDetail": "assets/products/ra-005-detail.webp",
    "price": 229,
    "desc": "Sun-warmed ochres and a hint of gilt make Solstice Depth feel lit from within. Built to order so the depth holds true in your own light, it is as durable as it is serene.",
    "collections": [
      "bestseller"
    ],
    "familyId": "golden-hour"
  },
  {
    "id": "ra-006",
    "sku": "RA #006",
    "name": "Ochre Weave",
    "family": "Terracotta & Earth",
    "accent": "#8E8274",
    "imgCard": "assets/products/ra-006-card.webp",
    "imgDetail": "assets/products/ra-006-detail.webp",
    "price": 249,
    "desc": "Matte, desert-warm texture makes Ochre Weave feel hand-shaped and honest. Hand-finished to order in archival pigment, it arrives ready to anchor a room.",
    "collections": [
      "bestseller"
    ],
    "familyId": "terracotta"
  },
  {
    "id": "ra-007",
    "sku": "RA #007",
    "name": "Goldleaf Veil",
    "family": "Golden Hour",
    "accent": "#AB9943",
    "imgCard": "assets/products/ra-007-card.webp",
    "imgDetail": "assets/products/ra-007-detail.webp",
    "price": 199,
    "desc": "Honeyed 3D texture turns Goldleaf Veil into a quiet source of warmth on the wall. Each piece is made to order, so the relief and color read exactly as you see them here.",
    "collections": [
      "bestseller"
    ],
    "familyId": "golden-hour"
  },
  {
    "id": "ra-008",
    "sku": "RA #008",
    "name": "Candle Drift",
    "family": "Golden Hour",
    "accent": "#AA9F8C",
    "imgCard": "assets/products/ra-008-card.webp",
    "imgDetail": "assets/products/ra-008-detail.webp",
    "price": 219,
    "desc": "Soft metallic highlights drift across Candle Drift, catching the late-afternoon light. Crafted to order and sealed for longevity, it suits a living room, studio, or hallway.",
    "collections": [
      "bestseller"
    ],
    "familyId": "golden-hour"
  },
  {
    "id": "ra-009",
    "sku": "RA #009",
    "name": "Abyssal Relief",
    "family": "Ocean & Sky",
    "accent": "#697F9F",
    "imgCard": "assets/products/ra-009-card.webp",
    "imgDetail": "assets/products/ra-009-detail.webp",
    "price": 239,
    "desc": "Cool, fluid relief gives Abyssal Relief a sense of depth, like tide lines on stone. Made to order on textured canvas, it makes a calm focal point above a sofa or console.",
    "collections": [
      "editors"
    ],
    "familyId": "ocean-sky"
  },
  {
    "id": "ra-010",
    "sku": "RA #010",
    "name": "Cinder Motion",
    "family": "Terracotta & Earth",
    "accent": "#8D715D",
    "imgCard": "assets/products/ra-010-card.webp",
    "imgDetail": "assets/products/ra-010-detail.webp",
    "price": 259,
    "desc": "Deep, earthen relief gives Cinder Motion its grounded, tactile presence. Built to order so the depth holds true in your own light, it is as durable as it is serene.",
    "collections": [
      "editors"
    ],
    "familyId": "terracotta"
  },
  {
    "id": "ra-011",
    "sku": "RA #011",
    "name": "Brick Fold",
    "family": "Terracotta & Earth",
    "accent": "#422F22",
    "imgCard": "assets/products/ra-011-card.webp",
    "imgDetail": "assets/products/ra-011-detail.webp",
    "price": 209,
    "desc": "Clay-toned layers build Brick Fold into a calm, rooted focal point. Hand-finished to order in archival pigment, it arrives ready to anchor a room.",
    "collections": [
      "editors"
    ],
    "familyId": "terracotta"
  },
  {
    "id": "ra-012",
    "sku": "RA #012",
    "name": "Tidal Echo",
    "family": "Ocean & Sky",
    "accent": "#334657",
    "imgCard": "assets/products/ra-012-card.webp",
    "imgDetail": "assets/products/ra-012-detail.webp",
    "price": 229,
    "desc": "Muted blue-greys flow across Tidal Echo in soft, layered currents. Each piece is made to order, so the relief and color read exactly as you see them here.",
    "collections": [
      "editors"
    ],
    "familyId": "ocean-sky"
  },
  {
    "id": "ra-013",
    "sku": "RA #013",
    "name": "Canyon Whisper",
    "family": "Terracotta & Earth",
    "accent": "#846C5C",
    "imgCard": "assets/products/ra-013-card.webp",
    "imgDetail": "assets/products/ra-013-detail.webp",
    "price": 249,
    "desc": "Rust and sienna ridges run through Canyon Whisper like sediment pressed into canvas. Crafted to order and sealed for longevity, it suits a living room, studio, or hallway.",
    "collections": [
      "editors"
    ],
    "familyId": "terracotta"
  },
  {
    "id": "ra-014",
    "sku": "RA #014",
    "name": "Sienna Layer",
    "family": "Terracotta & Earth",
    "accent": "#94786B",
    "imgCard": "assets/products/ra-014-card.webp",
    "imgDetail": "assets/products/ra-014-detail.webp",
    "price": 199,
    "desc": "Matte, desert-warm texture makes Sienna Layer feel hand-shaped and honest. Made to order on textured canvas, it makes a calm focal point above a sofa or console.",
    "collections": [
      "editors"
    ],
    "familyId": "terracotta"
  },
  {
    "id": "ra-015",
    "sku": "RA #015",
    "name": "Honey Emboss",
    "family": "Golden Hour",
    "accent": "#796B55",
    "imgCard": "assets/products/ra-015-card.webp",
    "imgDetail": "assets/products/ra-015-detail.webp",
    "price": 219,
    "desc": "Warm, light-catching relief gives Honey Emboss its glow, with fine ridges that shift through the day. Built to order so the depth holds true in your own light, it is as durable as it is serene.",
    "collections": [
      "editors"
    ],
    "familyId": "golden-hour"
  },
  {
    "id": "ra-016",
    "sku": "RA #016",
    "name": "Terra Ripple",
    "family": "Terracotta & Earth",
    "accent": "#5E4C3B",
    "imgCard": "assets/products/ra-016-card.webp",
    "imgDetail": "assets/products/ra-016-detail.webp",
    "price": 239,
    "desc": "Deep, earthen relief gives Terra Ripple its grounded, tactile presence. Hand-finished to order in archival pigment, it arrives ready to anchor a room.",
    "collections": [
      "editors"
    ],
    "familyId": "terracotta"
  },
  {
    "id": "ra-017",
    "sku": "RA #017",
    "name": "Solstice Form",
    "family": "Golden Hour",
    "accent": "#7F6436",
    "imgCard": "assets/products/ra-017-card.webp",
    "imgDetail": "assets/products/ra-017-detail.webp",
    "price": 259,
    "desc": "Sun-warmed ochres and a hint of gilt make Solstice Form feel lit from within. Each piece is made to order, so the relief and color read exactly as you see them here.",
    "familyId": "golden-hour"
  },
  {
    "id": "ra-018",
    "sku": "RA #018",
    "name": "Bloom Cascade",
    "family": "Botanical",
    "accent": "#507A50",
    "imgCard": "assets/products/ra-018-card.webp",
    "imgDetail": "assets/products/ra-018-detail.webp",
    "price": 209,
    "desc": "Living green relief gives Bloom Cascade an organic, garden-fresh calm. Crafted to order and sealed for longevity, it suits a living room, studio, or hallway.",
    "familyId": "botanical"
  },
  {
    "id": "ra-019",
    "sku": "RA #019",
    "name": "Goldleaf Current",
    "family": "Golden Hour",
    "accent": "#7D725D",
    "imgCard": "assets/products/ra-019-card.webp",
    "imgDetail": "assets/products/ra-019-detail.webp",
    "price": 229,
    "desc": "Honeyed 3D texture turns Goldleaf Current into a quiet source of warmth on the wall. Made to order on textured canvas, it makes a calm focal point above a sofa or console.",
    "familyId": "golden-hour"
  },
  {
    "id": "ra-020",
    "sku": "RA #020",
    "name": "Candle Strata",
    "family": "Golden Hour",
    "accent": "#916B35",
    "imgCard": "assets/products/ra-020-card.webp",
    "imgDetail": "assets/products/ra-020-detail.webp",
    "price": 249,
    "desc": "Soft metallic highlights drift across Candle Strata, catching the late-afternoon light. Built to order so the depth holds true in your own light, it is as durable as it is serene.",
    "familyId": "golden-hour"
  },
  {
    "id": "ra-021",
    "sku": "RA #021",
    "name": "Loam Texture",
    "family": "Terracotta & Earth",
    "accent": "#9A7252",
    "imgCard": "assets/products/ra-021-card.webp",
    "imgDetail": "assets/products/ra-021-detail.webp",
    "price": 199,
    "desc": "Clay-toned layers build Loam Texture into a calm, rooted focal point. Hand-finished to order in archival pigment, it arrives ready to anchor a room.",
    "familyId": "terracotta"
  },
  {
    "id": "ra-022",
    "sku": "RA #022",
    "name": "Cinder Surface",
    "family": "Terracotta & Earth",
    "accent": "#9F8A79",
    "imgCard": "assets/products/ra-022-card.webp",
    "imgDetail": "assets/products/ra-022-detail.webp",
    "price": 219,
    "desc": "Rust and sienna ridges run through Cinder Surface like sediment pressed into canvas. Each piece is made to order, so the relief and color read exactly as you see them here.",
    "familyId": "terracotta"
  },
  {
    "id": "ra-023",
    "sku": "RA #023",
    "name": "Maple Depth",
    "family": "Golden Hour",
    "accent": "#9B825A",
    "imgCard": "assets/products/ra-023-card.webp",
    "imgDetail": "assets/products/ra-023-detail.webp",
    "price": 239,
    "desc": "Warm, light-catching relief gives Maple Depth its glow, with fine ridges that shift through the day. Crafted to order and sealed for longevity, it suits a living room, studio, or hallway.",
    "familyId": "golden-hour"
  },
  {
    "id": "ra-024",
    "sku": "RA #024",
    "name": "Clay Weave",
    "family": "Terracotta & Earth",
    "accent": "#88786A",
    "imgCard": "assets/products/ra-024-card.webp",
    "imgDetail": "assets/products/ra-024-detail.webp",
    "price": 259,
    "desc": "Matte, desert-warm texture makes Clay Weave feel hand-shaped and honest. Made to order on textured canvas, it makes a calm focal point above a sofa or console.",
    "collections": [
      "new"
    ],
    "familyId": "terracotta"
  },
  {
    "id": "ra-025",
    "sku": "RA #025",
    "name": "Canyon Veil",
    "family": "Terracotta & Earth",
    "accent": "#66422A",
    "imgCard": "assets/products/ra-025-card.webp",
    "imgDetail": "assets/products/ra-025-detail.webp",
    "price": 209,
    "desc": "Deep, earthen relief gives Canyon Veil its grounded, tactile presence. Built to order so the depth holds true in your own light, it is as durable as it is serene.",
    "collections": [
      "new"
    ],
    "familyId": "terracotta"
  },
  {
    "id": "ra-026",
    "sku": "RA #026",
    "name": "Sienna Drift",
    "family": "Terracotta & Earth",
    "accent": "#9B7151",
    "imgCard": "assets/products/ra-026-card.webp",
    "imgDetail": "assets/products/ra-026-detail.webp",
    "price": 229,
    "desc": "Clay-toned layers build Sienna Drift into a calm, rooted focal point. Hand-finished to order in archival pigment, it arrives ready to anchor a room.",
    "collections": [
      "new"
    ],
    "familyId": "terracotta"
  },
  {
    "id": "ra-027",
    "sku": "RA #027",
    "name": "Honey Relief",
    "family": "Golden Hour",
    "accent": "#9C978D",
    "imgCard": "assets/products/ra-027-card.webp",
    "imgDetail": "assets/products/ra-027-detail.webp",
    "price": 249,
    "desc": "Sun-warmed ochres and a hint of gilt make Honey Relief feel lit from within. Each piece is made to order, so the relief and color read exactly as you see them here.",
    "collections": [
      "new"
    ],
    "familyId": "golden-hour"
  },
  {
    "id": "ra-028",
    "sku": "RA #028",
    "name": "Terra Motion",
    "family": "Terracotta & Earth",
    "accent": "#966C43",
    "imgCard": "assets/products/ra-028-card.webp",
    "imgDetail": "assets/products/ra-028-detail.webp",
    "price": 199,
    "desc": "Rust and sienna ridges run through Terra Motion like sediment pressed into canvas. Crafted to order and sealed for longevity, it suits a living room, studio, or hallway.",
    "collections": [
      "new"
    ],
    "familyId": "terracotta"
  },
  {
    "id": "ra-029",
    "sku": "RA #029",
    "name": "Dune Fold",
    "family": "Terracotta & Earth",
    "accent": "#A08065",
    "imgCard": "assets/products/ra-029-card.webp",
    "imgDetail": "assets/products/ra-029-detail.webp",
    "price": 219,
    "desc": "Matte, desert-warm texture makes Dune Fold feel hand-shaped and honest. Made to order on textured canvas, it makes a calm focal point above a sofa or console.",
    "collections": [
      "new"
    ],
    "familyId": "terracotta"
  },
  {
    "id": "ra-030",
    "sku": "RA #030",
    "name": "Ochre Echo",
    "family": "Terracotta & Earth",
    "accent": "#8E6445",
    "imgCard": "assets/products/ra-030-card.webp",
    "imgDetail": "assets/products/ra-030-detail.webp",
    "price": 239,
    "desc": "Deep, earthen relief gives Ochre Echo its grounded, tactile presence. Built to order so the depth holds true in your own light, it is as durable as it is serene.",
    "collections": [
      "new"
    ],
    "familyId": "terracotta"
  },
  {
    "id": "ra-031",
    "sku": "RA #031",
    "name": "Sediment Whisper",
    "family": "Terracotta & Earth",
    "accent": "#A07E5C",
    "imgCard": "assets/products/ra-031-card.webp",
    "imgDetail": "assets/products/ra-031-detail.webp",
    "price": 259,
    "desc": "Clay-toned layers build Sediment Whisper into a calm, rooted focal point. Hand-finished to order in archival pigment, it arrives ready to anchor a room.",
    "collections": [
      "new"
    ],
    "familyId": "terracotta"
  }
];
window.SITE.FAMILIES = [
  {
    "id": "all",
    "name": "All Artworks"
  },
  {
    "id": "ocean-sky",
    "name": "Ocean & Sky",
    "tag": "Cool, fluid tones drawn from sky and sea."
  },
  {
    "id": "botanical",
    "name": "Botanical",
    "tag": "Living greens that bring the outdoors in."
  },
  {
    "id": "golden-hour",
    "name": "Golden Hour",
    "tag": "Warm, sunlit hues of late afternoon."
  },
  {
    "id": "terracotta",
    "name": "Terracotta & Earth",
    "tag": "Grounding reds, clays and desert warmth."
  }
];
window.SITE.SIZES = [
  {
    "label": "Small · 12\"×16\" / 30×40cm",
    "add": 0
  },
  {
    "label": "Medium · 16\"×24\" / 40×60cm",
    "add": 60
  },
  {
    "label": "Large · 24\"×36\" / 60×90cm",
    "add": 140
  },
  {
    "label": "X-Large · 32\"×48\" / 80×120cm",
    "add": 240
  }
];
window.SITE.FORMATS = [
  {
    "label": "Rolled Canvas (Frameless)",
    "add": 0,
    "note": "Ships rolled, ready for your own frame."
  },
  {
    "label": "Stretched & Ready-to-Hang",
    "add": 40,
    "note": "Pre-stretched on a solid wood frame with hanging kit."
  },
  {
    "label": "Framed in Solid Wood",
    "add": 90,
    "note": "Finished floating frame, arrives wall-ready."
  }
];
